### ISSUE TITLE
Unable to authenticate with netlify lfs

### ISSUE THREAD

**Issue by jorisnoo** [netlify/netlify-credential-helper#38]
I'm using netlify lfs for a repository but was suddenly unable to retrieve the files via `git lfs fetch`.

A complete re-install of the netlify-cli and the credential helper as well as a fresh clone of the repository (and running `netlify lm:install`) dit not help, unfortunately.

`netlify status` confirms that the local repository is connected to the netlify site.

`netlify lm:info` returns:
```
  ✔ Checking Git version [2.23.0]
  ✔ Checking Git LFS version [2.8.0]
  ✔ Checking Git LFS filters
  ✔ Checking Netlify's Git Credentials version [0.1.8]
```

When I run `DEBUG=1 git lfs fetch`, it seems like the process is stuck in a loop. Starting with
```
msg="Initializing Netlify credential helper" args="[/Users/xxx/.netlify/helper/bin/git-credential-netlify erase]"
msg="Initializing Netlify credential helper" args="[/Users/xxx/.netlify/helper/bin/git-credential-netlify get]"
msg="Git input received" host=290e8dfa-3830-4ba9-a888-xxxxx.netlify.com protocol=https
```
it then gets a json response containing data about the site and outputs
```
msg="Writing output data" host=290e8dfa-3830-4ba9-a888-xxxxx.netlify.com password="39fb1a****************" protocol=https username=access-token
```

However it then immediately starts with initializing the credential helper again (as in the lines above) — and continues being stuck in this loop. Are the credentials not properly stored or how could I go about finding a solution for this issue?

I'm running macOS 10.14.6 (18G95) with node v10.16.3.

**Comment by jorisnoo** [comment]
All of a sudden, it was able to retrieve the credentials again.

**Comment by mraerino** [comment]
@jorisnoo this was happening because of a backend issue that we just fixed.
thanks for reporting and sorry for interrupting your work!
