### ISSUE TITLE
Runtime error: Slice bounds out of range

### ISSUE THREAD

**Issue by mraerino** [netlify/netlify-credential-helper#39]
## Actions

```
yarn global add netlify-cli
netlify plugins:install netlify-lm-plugin
netlify lm:install
git clone myrepo-with-lm
```

## Output

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/netlify/netlify-credential-helper/credentials.getCredentials(0x17696e0, 0xc00000c010, 0x1769720, 0xc00000c018, 0xc0005ffe38, 0xc000088840)
	/home/david/src/github.com/netlify/netlify-credential-helper/credentials/credentials.go:126 +0xd36
github.com/netlify/netlify-credential-helper/credentials.handleCommand(0x7ffeefbff7d1, 0x3, 0x17696e0, 0xc00000c010, 0x1769720, 0xc00000c018, 0x18, 0x165e200)
	/home/david/src/github.com/netlify/netlify-credential-helper/credentials/credentials.go:65 +0x127
github.com/netlify/netlify-credential-helper/credentials.HandleCommand()
	/home/david/src/github.com/netlify/netlify-credential-helper/credentials/credentials.go:52 +0x2db
main.main()
	/home/david/src/github.com/netlify/netlify-credential-helper/cmd/netlify-credential-helper/main.go:6 +0x20
```

This might be due to the fact that I'm not logged in. In that case that should be handled and documented better.

**Comment by djurosaur** [comment]
I have a same issue, both if im logged in, or logged out (Windows 10)

**Comment by swayhead** [comment]
Same problem here on MacOS

**Comment by erezrokah** [comment]
Hi @djurosaur and @swayhead, can you make sure you're running the latest CLI version [`v3.8.3`](https://github.com/netlify/cli/releases/tag/v3.8.3) by running `npm install netlify-cli -g`?

Then try
```
netlify logout
netlify login
netlify lm:install
netlify lm:setup
```

**Comment by swayhead** [comment]
Hi @erezrokah, 
that was obiously the point. After updating the CLI yesterday the clone went smoothly. Also, no asking for credentials regarding the Large Media stuff.
Thanks

**Comment by djurosaur** [comment]
hi @erezrokah ,
Works great now!
Thank you

**Comment by Nixinova** [comment]
This is a *really* bad error message, why do I get the stack trace of some other person's computer?

**Comment by mraerino** [comment]
i think multiple people reported this as fixed?
