### ISSUE TITLE
TypeError: Cannot read property 'slug' of undefined

### ISSUE THREAD

**Issue by jkaan** [netlify/netlify-credential-helper#46]
When running `netlify lm:setup` it redirects me to the browser and upon me pressing Authorize I see this error message in my terminal:

`TypeError: Cannot read property 'slug' of undefined`

![image](https://user-images.githubusercontent.com/3824068/97151990-90ea9200-1770-11eb-8d2f-ecf23e7f422a.png)

**Comment by erezrokah** [comment]
This was also reported in our CLI. See workaround [here](https://github.com/netlify/cli/issues/514#issuecomment-773851791) and we're currently working a solution.

**Comment by djurosaur** [comment]
@erezrokah workaround does not work, it still wants to authorize over browser (Windows 10)

**Comment by erezrokah** [comment]
Hello 👋 sorry for the delay in fixing this.
CLI version [`3.8.0`](https://github.com/netlify/cli/releases/tag/v3.8.0) address this issue.
Please comment if you're still experiencing issues after running:
```
netlify lm:setup
```
